<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MAIN" Id="{28507b62-cd61-4eba-97c0-4dd3a4048b0c}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	{ attribute: 'TcHmiSymbol.AddSymbol' }
	nCtx			: DINT;
	
	{ attribute: 'My.Custom.Attribute' }
	{ attribute: 'TcHmiSymbol.AddSymbol' }
	nAttribute		: DINT;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>